### ISSUE TITLE
Compile error through python script

### ISSUE THREAD

**Issue by H3rcu1es** [Exynos9611Development/android_kernel_samsung_universal9611-old#3]
**having this issue while using the build_kernel.py:**    

system : CachyOs(Arch linux)
Neutron-clang v19

traceback (most recent call last):
  File "./android_kernel_samsung_universal9611/build_kernel.py", line 184, in <module>
    main()
  File "./android_kernel_samsung_universal9611/build_kernel.py", line 150, in main
    popen_impl(make_common)
  File "./android_kernel_samsung_universal9611/build_kernel.py", line 32, in popen_impl
    raise RuntimeError(f"Command failed: {command}. Exitcode: {s.returncode}")
RuntimeError: Command failed: ['make', 'O=out', 'LLVM=1', '-j6', 'CROSS_COMPILE=aarch64-linux-gnu-', 'CC=clang', 'LD=ld.lld', 'AS=llvm-as', 'AR=llvm-ar', 'OBJDUMP=llvm-objdump', 'READELF=llvm-readelf', 'NM=llvm-nm', 'OBJCOPY=llvm-objcopy', '-j6']. Exitcode: 2

[12735_stderr.log](https://github.com/user-attachments/files/17675486/12735_stderr.log)
[12735_stdout.log](https://github.com/user-attachments/files/17675489/12735_stdout.log)

**Comment by revenger2000** [comment]
How did you solve this issue? I have the same.

Make clean...
Make defconfig...
Output log files: 62314_stdout.log, 62314_stderr.log
Traceback (most recent call last):
  File "/home/revenger2000/android_kernel_samsung_universal9611/build_kernel.py", line 184, in <module>
    main()
  File "/home/revenger2000/android_kernel_samsung_universal9611/build_kernel.py", line 148, in main
    popen_impl(make_defconfig)
  File "/home/revenger2000/android_kernel_samsung_universal9611/build_kernel.py", line 32, in popen_impl
    raise RuntimeError(f"Command failed: {command}. Exitcode: {s.returncode}")
RuntimeError: Command failed: ['make', 'O=out', 'LLVM=1', '-j8', 'CROSS_COMPILE=aarch64-linux-gnu-', 'CC=clang', 'LD=ld.lld', 'AS=llvm-as', 'AR=llvm-ar', 'OBJDUMP=llvm-objdump', 'READELF=llvm-readelf', 'NM=llvm-nm', 'OBJCOPY=llvm-objcopy', '-j8', 'vendor/m31_defconfig', 'vendor/grass.config', 'vendor/m31.config', 'vendor/ksu.config']. Exitcode: 2
